---
matrix:
  include:
    - before_script:
        - 'cd scala-maven'
      jdk: oraclejdk8
      language: java
      script: 'mvn clean package'
      cache:
        directories:
          - $HOME/.m2
    - before_script:
        - 'cd scala-docker'
      jdk: oraclejdk8
      language: java
      services:
        - docker
      script: 'mvn clean compile jib:dockerBuild'
      cache:
        directories:
          - $HOME/.m2
    - before_script:
        - 'cd scala-basics'
      jdk: oraclejdk8
      language: scala
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
