matrix:
  include:
    language: java
    before_script:
      - cd scala-maven
    jdk:
      - openjdk8
    cache:
      directories:
        - $HOME/.m2
    language: scala
    before_script:
      - cd scala-basics
    cache:
      directories:
        - $HOME/.ivy2/
        - $HOME/.sbt/cache/
        - $HOME/.sbt/boot/
        - $HOME/.sbt/launchers/